### ISSUE TITLE
How to nix-build w/ Flake and Overlay

### ISSUE THREAD

**Issue by SmolPatches** [polygon/nix-buildproxy#3]
I successfully installed the overlay in my configuration.nix by passing the default overlay from my flake as an input as you specified on your github.

I followed the steps to get a list of urls for proxycontent but now, I am having a hard time actually building w/ the default.nix I have.
default.nix
```
{ buildproxy, stdenv, cmake, libpcap, pkg-config, yacc, openssl,git }:
let
  buildproxy = lib.mkBuildproxy ./proxy_content.nix;
in
stdenv.mkDerivation  {
    name = "pppwn";
    src = ./.;
    prePatch = ''
      source ${buildproxy}
    '';
    nativeBuildInputs =  [ buildproxy openssl cmake pkg-config git libpcap ];
    buildInputs = [
	yacc
	libpcap
    ];
}
```
Build command, `nix-build --expr '(import <nixpkgs> {}).callPackage ./default.nix {}'`
```
       error: attribute 'mkBuildproxy' missing

       at /home/watashi/Areas/PS4/PPPwn_cpp/default.nix:3:16:

            2| let
            3|   buildproxy = lib.mkBuildproxy ./proxy_content.nix;
             |            
```
I am unaware of what am doing something wrong here, do I need to do something else to pass the nixpkgs w/ the overlay that my system is using to nix-build?
configuration.nix where the overlay was passed from the flake.
```
{ inputs, config, pkgs, ... }:

{
  # Allow unfree packages
  nixpkgs.config = {
    allowUnfree = true;
    allowBroken = false;
  };
  nixpkgs.overlays = [
    # use ungoogled chromium
    (final: prev: { chromium = prev.ungoogled-chromium.override { enableWideVine = true; }; })
    inputs.nix-buildproxy.overlays.default
  ];
...
```

**Comment by polygon** [comment]
Are you sure that `import <nixpkgs>` uses the same Nixpkgs instance that was used to build your system? I believe that this is not the case, though I never used Nix with channels instead of Flakes so my knowledge here is rather limited.

I think the easiest way (if possible) would be to turn the default.nix you have into a Flake and then add nix-buildproxy as an input.

**Comment by SmolPatches** [comment]
Ah I see, I opted for default.nix because I thought nix-build would simplify the process of using impure things like proxy_content.nix.

Is this what you had in mind for in order to run the build? But here, I am confused about how to use proxy_content.nix within a flake.
```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    nix-buildproxy.url = "github:polygon/nix-buildproxy";
  };

  outputs = inputs@{ self, nixpkgs, nix-buildproxy, ... }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs {
        inherit system;
        overlays = [ nix-buildproxy.overlays.default ];
      };
      buildproxy = pkgs.lib.mkBuildproxy ./proxy_content.nix;
    in
    {
      packages."x86_64-linux".default = pkgs.stdenv.mkDerivation {
        name = "pppwn";
        src = ./.;
        prePatch = ''
          source ${buildproxy}
        '';
        nativeBuildInputs = with pkgs; [ openssl cmake pkg-config git libpcap ];
        buildInputs = with pkgs;[
          yacc
          libpcap
        ];
      };
    };
}
```
Running this obviously fails because of the missing proxy_content.nix that is present in my directory but invisible to the flake.

```console
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'pppwn'
         whose name attribute is located at /nix/store/z71lmgd0ydfnax1b13zbrls5idf1y7ak-source/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'prePatch' of derivation 'pppwn'

         at /nix/store/40ddaazvbhan7gq57qfr3hxq1mky3p8b-source/flake.nix:21:9:

           20|         src = ./.;
           21|         prePatch = ''
             |         ^
           22|           source ${buildproxy}

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: getting status of '/nix/store/40ddaazvbhan7gq57qfr3hxq1mky3p8b-source/proxy_content.nix': No such file or directory
```

**Comment by polygon** [comment]
`proxy_content.nix` is not impure. It's meant to be part of your Flake to make sure that others get exactly the same responses from nix-buildproxy that you did.

Your code above looks fine. If you add proxy-content.nix to the Flake, it should work as intended.

**Comment by SmolPatches** [comment]
OH I just needed to git add proxy_content.nix so the flake can see it, thanks for the help!
